# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Linting and Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Installing packages
        run: yarn install

      - name: Linting code
        run: yarn lint

      - name: Linting styles
        run: yarn lint:style

      - name: Validating TypeScript
        run: yarn tsc --noEmit

      - name: Running Tests
        run: yarn test:ci

      - name: Building App
        run: yarn build
